import turtle
 
carro = turtle.Turtle()
 
#Parte superior rectangular
carro.color('#2B2BF6')
carro.fillcolor('#2B2BF6')
carro.penup()
carro.goto(0,0)
carro.pendown()
carro.begin_fill()
carro.forward(370)
carro.left(90)
carro.forward(50)
carro.left(90)
carro.forward(370)
carro.left(90)
carro.forward(50)
carro.end_fill()
 
#Ventana y techo
carro.penup()
carro.goto(100, 50)
carro.pendown()
carro.setheading(45)
carro.forward(70)
carro.setheading(0)
carro.forward(100)
carro.setheading(-45)
carro.forward(70)
carro.setheading(90)
carro.penup()
carro.goto(200, 50)
carro.pendown()
carro.forward(49.50)
 
#LLantas
carro.penup()
carro.goto(100, -10)
carro.pendown()
carro.color('#000000')
carro.fillcolor('#000000')
carro.begin_fill()
carro.circle(20)
carro.end_fill()
carro.penup()
carro.goto(300, -10)
carro.pendown()
carro.color('#000000')
carro.fillcolor('#000000')
carro.begin_fill()
carro.circle(20)
carro.end_fill()

carro.hideturtle()